/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mariangolea.fintracker.banks.pdfparser.cmdsupport;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Command line support for parsing supported arguments.
 *
 * @author mariangolea@gmail.com
 */
public final class CmdArgParser {

    public static final String INPUT_FOLDER_ARG = "-folder";
    public static final String FOLDER_NAME_SEPARATOR = "=";
    public static final String FOLDER_PATH_ESCAPE = "\"";
    public static final String SUPPORTED_FILE_EXTENSION = ".pdf";

    /**
     * Retrieve the list of all .pdf files found in the folders specified in
     * command line.
     * <br> Folder specification needs to adhere to the format:
     * -folder="somefolder".
     *
     * @param args list of strings each depicting one single folder definition.
     * @return all pdf files found in all received folders.
     */
    public List<File> getPDFFiles(String[] args) {
        if (args == null || args.length < 1) {
            printError();
        }

        final List<File> folderFiles = getFolderFiles(args);
        final List<File> pdfFiles = new ArrayList<>();

        folderFiles.forEach(folderFile -> {
            File[] pdfsPerFolder = folderFile.listFiles((File dir, String name) -> {
                return name.endsWith(SUPPORTED_FILE_EXTENSION);
            });
            pdfFiles.addAll(Arrays.asList(pdfsPerFolder));

        });

        System.out.println("Found following pdf files in all input folders: ");
        pdfFiles.forEach(f -> {
            System.out.println("    " + (pdfFiles.indexOf(f) + 1) + ". " + f.getAbsolutePath());
        });
        System.out.println();

        return pdfFiles;
    }

    private void printError() {
        System.out.println("Please input the path to a folder which contains PDF reports generated by supported banks (only ING for now).");
        System.out.println("Absolute folder path needs to be specified: -folder=\"pathOnYourOperatingSystem\" ");
        System.out.println("-inputFolder can be used multiple times to designate more folders: -folder=\"sss\" -folder=\"fff\"");
        System.exit(1);
    }

    protected List<File> getFolderFiles(String[] args) {
        final List<File> folderFiles = new ArrayList<>();
        for (String arg : args) {
            String[] argParams = arg.split(FOLDER_NAME_SEPARATOR);
            if (argParams.length != 2 || !INPUT_FOLDER_ARG.equals(argParams[0])) {
                printError();
            }

            String folderPath = argParams[1].replaceAll("\"", "");
            File folderFile = new File(folderPath);
            if (!folderFile.exists() || !folderFile.isDirectory()) {
                printError();
            } else {
                folderFiles.add(folderFile);
            }
        }

        System.out.println("Found following input folders: ");
        folderFiles.forEach(f -> {
            System.out.println("    " + (folderFiles.indexOf(f) + 1) + ". " + f.getAbsolutePath());
        });
        System.out.println();
        return folderFiles;
    }
}
